config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'

  # 実施コマンド：rails g controller PostImages new index show
  # get 'post_images/new'
  # get 'post_images/index'
  # get 'post_images/show'

  # resources メソッドは、ルーティングを一括して自動生成してくれる機能

  # onlyオプションを使用することで、生成するルーティングを限定することができます。
  # この場合、only の後に配列で記述されている"new","index","show"のアクション以外は、ルーティングが行われません。
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do

    # 今まではresourcesでしたが、ここでは、resourceとなっている点に注目してください。
    # 単数形にすると、/:idがURLに含まれなくなります。

    # コメント機能では「1人のユーザが１つの投稿に対して何度でもコメントできる」という仕様だったため、
    # destroyをする際にidを受け渡して「どのコメントを削除するのか」を指定する必要がありました。
    # destroyアクションの場合、URLは'/post_images/:post_image_id/post_comments/:id'のようになっており、URLの最後に/:idが含まれます。
    # コントローラで「params[:id]」と記述することで、このURLに含まれる:idを取得できるのでした。

    # しかし、いいね機能の場合は「1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様であるため、
    # destroyをする際にもユーザーidと投稿(post_image)idが分かれば、どのいいねを削除すればいいのかが特定できます。
    # そのため、いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、
    # resourcesではなくresourceを使ってURLに/:idを含めない形にしています。

    # このように、resourceは「それ自身のidが分からなくても、関連する他のモデルのidから特定できる」といった場合に用いることが多いです。
    resource :favorites, only: [:create, :destroy]

    # post_image_favorites DELETE /post_images/:post_image_id/favorites(.:format)                           favorites#destroy
    #                      POST   /post_images/:post_image_id/favorites(.:format)                           favorites#create

    # resourcesで指定したコントローラ名に、resourceで指定したコントローラ名が続くURLが生成されるのが確認できます。
    # resources(複数形)の場合ではdestroyアクションのURLは最後に/:idが付いていたことを思い出してください。
    # resourceにしたことで/:idがない形でURLが生成されているのが確認できます。

    # コメントは、投稿画像に対してコメントされます。このため、post_commentsは、post_imagesに結びつきます。 以下のように親子関係になります。
    resources :post_comments, only: [:create, :destroy]

    # 以下コマンドを実行し、実際にURLを確認しましょう。
    # 今回追記したpost_comments関連のルーティングは以下のようになります。

    # post_image_post_comments POST   /post_images/:post_image_id/post_comments(.:format)     post_comments#create

    # 親のresourcesで指定したコントローラ名に、子のresourcesで指定したコントローラ名が続くURLが生成されるのが確認できます。
    # このような親子関係を、「ネストする」と言います。
    # 上記のようなネストしたURLを作成することでparams[:post_image_id]でPostImageのidが取得できるようになります。


  end
  # get 'users/show'
  # get 'users/edit'

  resources :users, only: [:show, :edit, :update]

  get '/homes/about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post_image.rb
class PostImage < ApplicationRecord

    # 1対１(単数枚画像投稿)で関連付けるという宣言
    # シンボルで指定するカラム名でそのデータを扱うので、わかりやすい名前にします。
    # （画像なら :image、動画なら :movie、アバターなら :avatar など）
    has_one_attached :image

    belongs_to :user

    # belongs_to とは

    # 今回も新たに、"belongs_to"というメソッドが出てきました。
    # "belongs to〜"とは、直訳すると「〜に属する」という意味です。

    # has_many の時と同様、"belongs_to :user"という記述を見ていきましょう。
    # 直訳すると、「ユーザーに属する」ということになります。

    # has_many とは逆に、1:N の「N」側にあたるモデルに、belongs_to を記載する必要があります。
    # belongs_to は、PostImage モデルから user_id に関連付けられていて、User モデルを参照することができます。
    # PostImage モデルに関連付けられるのは、1 つの User モデルです。
    # このため、単数形の「user」になっている点に注意しましょう。

    # PostImageモデル／PostCommentモデル(1:N)
    # 1つの投稿画像に対して、複数のコメントを設定できます。 これも、1:Nの関係です。
    has_many :post_comments, dependent: :destroy

    has_many :favorites, dependent: :destroy

    #shop_nameが存在しているかを確認するバリデーション
    validates :shop_name, presence: true

    #imageが存在しているかを確認するバリデーション
    validates :image, presence: true

    # このメソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べます。
    # 存在していればtrue、存在していなければfalseを返すようにしています。
    # Viewの作成で利用します。
    def favorited_by?(user)

        favorites.exists?(user_id: user.id)

    end

    def get_image

        # get_imageというメソッドを作成しました。
        # これはアクションとは少し違い、特定の処理を名前で呼び出すことができるようになります。
        # PostImageモデルの中に記述することで、カラムを呼び出すようにこの処理（メソッド）を呼び出すことができるようになります。

        # 例えば、post_imagesテーブルでIDが1のデータを持っていて、そのデータから保存された画像を表示させたい場合
        # 以下のように記述することができます。

        # # ID:1のレコードを取得し、@post_imageに格納する
        # @post_image = PostImage.find(1)

        # # @post_imageに含まれるイメージを表示させるメソッドを実行する
        # # カラムのように、インスタンス変数の後に"."をつけて、その後にメソッド名を繋げる
        # @post_image.get_image

        # if image.attached?
        #     image
        # else
        #     'no_image.jpg'
        # end

        #  画像が存在しない場合に表示する画像をActiveStorageに格納する
        # 今回作成するMeshiterroでは、画像のサイズ変更をRailsで行います。

        # ですが、上記で記述したメソッドだとRailsで画像のサイズ変更を行うことができないため
        # no_image.jpgをActiveStorageに格納するためにコードを次のように書き換えます。
        # ※既に記述しているアソシエーションの部分は、そのまま残しておきましょう。

        # unless文は条件式が偽の場合の処理を記述
        unless image.attached?

            file_path = Rails.root.join('app/assets/images/no_image.jpg')

            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')

        end

        image

        # このメソッドの内容は、画像が設定されない場合はapp/assets/imagesに格納されている
        # no_image.jpgという画像をデフォルト画像としてActiveStorageに格納し、格納した画像を表示するというものです。

    end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new

    # データを受け取り新規登録するためのインスタンス作成
    # postimage.newではない。モデルのclass名（PostImage）.new が正しい。
    @post_image = PostImage.new

  end

  # 投稿データの保存
  def create

    # 投稿するデータを PostImage モデルに紐づくデータとして保存する準備をしていて
    # フォームに入力されたデータ(shop_name や caption,image など)が、@post_image に格納されることになっています。
    @post_image = PostImage.new(post_image_param)

    # current_user について
    # current_user は、コードに記述するだけで、ログイン中のユーザーの情報を取得できる便利な記述です。
    # ヘルパーメソッドと呼ばれるものの一種で、devise をインストールすることで使えるようになります。

    # この current_user は、ログイン中のユーザー情報を取得することができるため、current_user.id と記述することで
    # ログインユーザーの id を取得することができます。
    # また、User モデルに紐付いたカラムの情報も取得できるため、例えば以下のような使い方ができます。

    # current_user.name : 今ログインしているユーザーの名前を表示
    # current_user.email : 今ログインしているユーザーのメールアドレスを表示
    # ※ devise のヘルパーメソッドであるため、devise を導入しないと使用することができません。

    # @post_image.user_id は、PostImage モデルに紐づいた user_id の値を操作できる
    # current_user は、現在ログイン中のユーザーに関する情報を取得できる
    @post_image.user_id = current_user.id

    # ◆ここで、user_id が何であったかを思い出してみましょう。◆
    #   user_id は、PostImage モデルを作成時に作ったカラムであること
    #   user_id は、ユーザーを ID で特定するために使用するカラムであること

    #   つまり、 user_idは画像投稿を行う際に、「どのユーザーが投稿したのか」を「ユーザーの ID で判断する」ためのカラムであることがわかります。

    #   改めて説明となりますが、@post_image は、PostImage.new によって生成された、PostImage の空のモデルです。
    #   空のモデルでは、PostImage モデルで定義したカラムを@post_image.user_idのように、"[モデル名].[カラム名]"
    #   という形で繋げることで、保存するカラムの中身を操作することができます。

    # 2 つ前の章で作成した PostImage モデルには、以下のカラムがありました。

    # カラム名	データ型	カラムの説明
    # id	      integer	  投稿画像を識別する ID
    # shop_name	string	  お店の名前
    # caption	  text	    画像の説明
    # user_id	  integer	  投稿したユーザを識別する ID（users テーブルの id を保存する）

    # つまり、この場合は次のようになります。
    #   @post_image.shop_name : お店の名前
    #   @post_image.caption : 画像の説明
    #   @post_image.user_id : 投稿したユーザを識別する ID

    # これらをコードの中に記述することで、PostImage モデルに紐づくカラムの値を取得したり、逆に値を代入することができるということになります。

    # @post_image.save

    if @post_image.save

      # 一覧画面へ遷移する。
      redirect_to post_images_path

    else

      render :new

    end

  end

  def index

    # 投稿一覧で表示する全ての画像をコントローラで取得します。
    # post_images_controller.rbファイルのindexに、以下のコードを記述します。
    # これで、タイムライン上に表示する投稿データを取得できるようになります。

    # @post_images = PostImage.all

    # indexアクションの中では、postimagesテーブル内の全データが取得されていました。
    # これを、1ページ分の決められた数のデータだけを、新しい順に取得するように変更しています。
    # pageメソッドは、kaminariをインストールしたことで使用可能になったメソッドです。
    @post_images = PostImage.page(params[:page])

  end

  def show

    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new

  end

  def destroy

    # 削除するPostImageレコードを取得
    @post_image = PostImage.find(params[:id])
    # PostImageレコードを削除
    @post_image.destroy
    # 一覧画面へ遷移する。
    redirect_to post_images_path

  end

  private

  # 投稿データのストロングパラメータ
  def post_image_param

    params.require(:post_image).permit(:shop_name, :caption)

    # ストロングパラメータの設定
    # post_image_paramsメソッドでは、フォームで入力されたデータが、投稿データとして許可されているパラメータかどうかをチェックしています。

    # PostImageモデルへ保存した後、投稿一覧画面へリダイレクトします。
    # ※この時点で投稿すると投稿一覧画面が存在しないためエラーになります。投稿一覧画面は次で作成していきます。

  end

end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">

    <!--投稿部分にはBootstrapのcardというコンポーネントを使用しています。-->
    <!--画像と、その詳細について表示するときなどに多く使用されるレイアウトです。-->
    <!--カードで表示したい部分を囲っているdiv要素は以下のようになっています。-->

    <!--ここで重要なのは「card」classです。-->
    <!--「card」classには以降の子要素で使用するclassが依存する形になります。-->

    <!--その他のclassはサイズ、padding、margin、影を付けるといったcardの構成には関係のないclassです。-->

    <!--この「card」classを指定さえすれば、その中の要素で使用するものは自由に組むことができます。-->
    <!--今回のMeshiterroでは投稿に関する情報を「card-body」classで包括し、その中で投稿したユーザーのアイコン画像を表示する領域と投稿に関する情報を表示する領域をcolによってグリッドで分けています。-->

    <!--投稿に関する情報を表示する領域でcard-titleやcard-textというclassを使用していますが、こちらも必ず使わなければいけないというわけでは、ありません。-->

    <!--cardコンポーネントが提供するclassの詳細については公式を確認してください。-->

    <%= link_to post_image_path(post_image.id) do %>
      <%= image_tag post_image.get_image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag post_image.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<!--app/views/post_imagesフォルダのindex.html.erbファイルで、部分テンプレートを呼び出せるように設定します。 以下のように記述します。-->

<%= render 'list', post_images: @post_images %>

<!--この一行について解説すると下のようになります。-->

<!-- %= render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値] %>-->

<!--テンプレートファイルを呼び出す記述-->

 <!--部分テンプレートファイルを呼び出すには、renderを使う-->
 <!--'list'で部分テンプレートのパスを記述する-->
 <!--その際、アンダースコアは省略する-->
 <!-- また、post_images/list.html.erbが本来の呼び出し方だが、拡張子は省略でき、同じフォルダ内から呼び出す場合はフォルダ名も省略できる-->
 <!-- ローカル変数（'post_images'）に渡すインスタンス変数（@post_images）を指定する-->

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
     <!--フォーム部分を構成するclassには特別なルールは存在せず、自由に組み付けてもフォームとして機能しなくなることはありません。-->
    <!--ですが基本的には、フォーム部品にはform-controlを使用し、それを囲う部分にはform-groupを使用します。-->
    <!--※今回のMeshiterroの例ではform-groupを使用していません。-->

    <!--今回それよりも、注目したい箇所は以下のコードのcolを指定しているところです。-->
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">

    <!--colのclassが二つあります。-->

    <!--col-sm-10-->
    <!--col-md-5-->
    <!--これは画面幅が切り替わったときに、入力フォームの幅などを調節するためにcolを二つ指定しています。-->

    <!--col-sm-10-->
    <!--画面幅が576px以上のときに12分割したグリッドの10分割分の幅をとる-->
    <!--※このときの10分割分の幅は親要素であるrowの幅に依存します。-->

    <!--col-md-5-->
    <!--画面幅が768px以上のときに12分割したグリッドの5分割分の幅をとる-->
    <!--※このときの10分割分の幅は親要素であるrowの幅に依存します。-->

    <!--復習になりますが、Bootstrap は幅を12 個のグリッド に分割するレイアウトシステムを持ちます。-->

    <!--「col」classの指定ではcol-[ブレークポイント]-[カラム数（分割されたグリッド数）]という形式でclassを指定します。-->
    <!--つまり、今回の例では画面幅が576px以上〜768px未満の時に10カラムの幅をとり、768px以上では5カラムの幅をとる。ということになります。-->

    <!--例えば、-->

    <!--親要素はrowのclassを持っていて600px、-->
    <!--子要素はcol-md-5のclassを持っている.-->
    <!--という場合の子要素の幅の計算式はいくつかありますが、-->
    <!--「12等分したうちの5個分」という考え方では-->

    <!--600 ÷ 12 × 5 = 250-->
    <!--となり250pxの幅になります。-->

    <!--このように複数のcolをブレークポイントごとに指定することで画面幅に応じたレイアウトを提供することができます。（レスポンシブレイアウト）-->
    <!--ログイン、新規登録は投稿フォームと似たような構成になっていますので、投稿フォームを参考にするといいでしょう。-->

      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post_image do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <!--'%Y/%m/%d'の記述で、年/月/日のフォーマットへ変換します。 %Y、%m、%dは、日時のフォーマット指定によく使われます。覚えておきましょう。-->
  <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>

  <!--もし、投稿者 == 現在ログインしているユーザ だったら-->
  <!--    削除ボタン-->
  <!--終わり-->
  <% if @post_image.user == current_user %>
    <!--削除機能の作成は終わりましたが、これでは削除を実行する手段がないため、詳細画面に削除を実行するためのリンクを追記します。-->
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>

  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>

<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>
</div>

<!--form_withに対して、[@post_image,@post_comment]のように、配列でインスタンス変数を2つ指定している点に注意してください。 -->
<!--コメントは、post_imageに結びついたpost_commentであるため、2つ用意する必要があります。 -->
<!--また、post_commentをcreateするためのリクエストは、ルーティングもネスト（親子関係）しているため、上記2つの情報が必要になります-->
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>