config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'

  # 実施コマンド：rails g controller PostImages new index show
  # get 'post_images/new'
  # get 'post_images/index'
  # get 'post_images/show'

  # resources メソッドは、ルーティングを一括して自動生成してくれる機能

  # onlyオプションを使用することで、生成するルーティングを限定することができます。
  # この場合、only の後に配列で記述されている"new","index","show"のアクション以外は、ルーティングが行われません。
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do

    # 今まではresourcesでしたが、ここでは、resourceとなっている点に注目してください。
    # 単数形にすると、/:idがURLに含まれなくなります。

    # コメント機能では「1人のユーザが１つの投稿に対して何度でもコメントできる」という仕様だったため、
    # destroyをする際にidを受け渡して「どのコメントを削除するのか」を指定する必要がありました。
    # destroyアクションの場合、URLは'/post_images/:post_image_id/post_comments/:id'のようになっており、URLの最後に/:idが含まれます。
    # コントローラで「params[:id]」と記述することで、このURLに含まれる:idを取得できるのでした。

    # しかし、いいね機能の場合は「1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様であるため、
    # destroyをする際にもユーザーidと投稿(post_image)idが分かれば、どのいいねを削除すればいいのかが特定できます。
    # そのため、いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、
    # resourcesではなくresourceを使ってURLに/:idを含めない形にしています。

    # このように、resourceは「それ自身のidが分からなくても、関連する他のモデルのidから特定できる」といった場合に用いることが多いです。
    resource :favorites, only: [:create, :destroy]

    # post_image_favorites DELETE /post_images/:post_image_id/favorites(.:format)                           favorites#destroy
    #                      POST   /post_images/:post_image_id/favorites(.:format)                           favorites#create

    # resourcesで指定したコントローラ名に、resourceで指定したコントローラ名が続くURLが生成されるのが確認できます。
    # resources(複数形)の場合ではdestroyアクションのURLは最後に/:idが付いていたことを思い出してください。
    # resourceにしたことで/:idがない形でURLが生成されているのが確認できます。

    # コメントは、投稿画像に対してコメントされます。このため、post_commentsは、post_imagesに結びつきます。 以下のように親子関係になります。
    resources :post_comments, only: [:create, :destroy]

    # 以下コマンドを実行し、実際にURLを確認しましょう。
    # 今回追記したpost_comments関連のルーティングは以下のようになります。

    # post_image_post_comments POST   /post_images/:post_image_id/post_comments(.:format)     post_comments#create

    # 親のresourcesで指定したコントローラ名に、子のresourcesで指定したコントローラ名が続くURLが生成されるのが確認できます。
    # このような親子関係を、「ネストする」と言います。
    # 上記のようなネストしたURLを作成することでparams[:post_image_id]でPostImageのidが取得できるようになります。


  end
  # get 'users/show'
  # get 'users/edit'

  resources :users, only: [:show, :edit, :update]

  get '/homes/about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!--%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!--上記の変更で、stylesheet_link_tagをstylesheet_pack_tagとしていますが、これが何をしているか解説します。-->
    <!--stylesheet_link_tagの場合cssファイルは、app/assets 配下のファイルを参照します。-->
    <!--stylesheet_pack_tagの場合は、app/javascript 配下のファイルを参照するようになります。-->

    <!--このように記述するとapp/assets、app/javascriptを参照するようになります。-->

    <!--どちらが正しいというのは一概に言えません。-->
    <!--現場ではプロジェクトによってファイルの管理体制は様々です。-->
    <!--知識として、知っておくべきことなので、覚えておいてください。-->

    <!--stylesheet_pack_tagのみの記述で独自のcssを読み込ませる方法を紹介しておきます。-->

    <!--1.app/javascript/stylesheets/application.scssにcssを記述する-->
    <!--2.app/javascript/packs/application.jsに追加したcssファイルをimport で追加する-->


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!--<body>-->
  <body class="d-flex flex-column vh-100">
    <!-- % if user_signed_in? % は、devise 側で用意しているヘルパーメソッドです。-->
    <!--devise の機能を使ってログインしているか、ログインしていないかを判断し、どちらかによってブラウザに表示する内容を変更することができます。-->
    <!--具体的には、以下のような処理を行なっています。-->

    <!--ログイン済みならば true が、ログインしていなければ false が返されます。-->
    <!--ログイン済みの場合、% if user_signed_in? % から % else % 間のコードが表示されます。-->
    <!--ログインしていない場合、% else % から  % end % 間のコードが表示されます。-->
  <!--<header>-->
    <header class="shadow-sm">

      <nav class="navbar navbar-expand-lg navbar-light">

        <!--navbar-->
        <!--navbar-expand-lg-->
        <!--navbar-light-->
        <!--それぞれのclassの役割は以下になります。-->

        <!--navbar-->
        <!--ナビゲーションバーの表示-->

        <!--navbar-expand-[ブレークポイント]-->
        <!--指定したブレークポイント（画面幅）に応じてナビゲーションバー、ナビゲーションアイコン（ハンバーガーメニュー）を切り替えて表示-->

        <!--navbar-[カラースキーム]-->
        <!--ナビゲーションのカラースキームの指定-->

        <!--この3つのclassはセットで使用するように覚えておくといいです。-->
        <!--例えばですが、navbar-[カラースキーム]の指定がないと画面幅が変化したときに、-->
        <!--ナビゲーションアイコン（ハンバーガーメニュー）に配色が当たらないために画面上には要素は存在するが、-->
        <!--見えないといったことが起こります。-->

        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>

          <!--navbar-brand-->
          <!--p-3-->
          <!--それぞれのclassの役割は以下になります。-->

          <!--navbar-brand-->
          <!--ロゴに使用されるnavbarのサポートclass-->

          <!--p-[サイズ]-->
          <!--paddingの指定-->
          <!--※今回の場合は上下左右に対してサイズ指定されたpaddingが適応されています。-->
          <!--上、下、左、右、上下、左右という指定の仕方もできます。-->
          <!--詳細は公式を確認してみましょう。-->
          <!--https://getbootstrap.jp/docs/4.5/utilities/spacing/-->

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!--button要素のnavbar-togglerとspan要素のnavbar-toggler-iconがナビゲーションアイコン（ハンバーガーメニュー）の見た目に関わるところです。-->
          <!--以下のように覚えておくといいでしょう。-->

          <!--navbar-toggler-->
          <!--ナビゲーションアイコン（ハンバーガーメニュー）の枠部分-->

          <!--navbar-toggler-icon-->
          <!--ナビゲーションアイコン（ハンバーガーメニュー）の三本線部分-->
          <!--※この三本線はnavbar-toggler-iconのclassに対してbackground-imageで画像が割り当てられています。-->
          <!--検証ツールでnavbar-toggler-iconのclassを確認すると分かやすいです。-->

          <!--次にナビゲーションアイコンの開いたり、閉じたりする動作と見た目の部分についてです。-->
          <!--button要素と関係するため、合わせて見ていきましょう。-->

          <div class="collapse navbar-collapse" id="navbarNavDropdown">

          <!--ナビゲーションアイコンの開閉する動作についてはBootstrapとjQueryが内部的に行っている部分です。-->
          <!--ここは複雑な仕組みのため、以下のように簡単に覚えておくといいです。-->

          <!--  ナビゲーションアイコンを開く前に隠しておきたいメニューは「collapse」classが付与された要素の中に入れておく-->
          <!--  「collapse」classを付与している要素に任意のidを付与する-->
          <!--  付与したidは「navbar-toggler」classが付与される要素のdata-targetに指定する（頭にセレクタ#をつける）-->
          <!--   「navbar-toggler」classが付与される要素にdata-toggle="collapse"、data-target="#[id名]"、aria-controls="[id名]"、aria-expanded="false"、aria-label="Toggle navigation"-->
          <!--※この内data-toggle="collapse"、data-target="#[id名]"は必ず指定しなければ、ナビゲーションアイコンの開閉を行うことができませんので、注意しましょう。-->
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>